#!/bin/sh
# generate_toml.sh - Generate frpc TOML config from UCI config
# Compatible with frp >= 0.52.0 (TOML-based configuration)
# UCI config: /etc/config/frpc
# Output: /etc/frp/frpc.toml
#
# IMPORTANT: This script uses POSIX sh only (no bashisms).
# On OpenWrt, /bin/sh is busybox ash which does NOT support:
#   - bash arrays (declare -a, arr=())
#   - here-strings (<<<)
#   - read -ra
# All string operations use POSIX-compatible techniques.

set -e

UCI_CONF="frpc"
OUTPUT="/etc/frp/frpc.toml"
OUTPUT_TMP="${OUTPUT}.tmp"
CONF_DIR="/etc/frp"

mkdir -p "${CONF_DIR}"

# ──────────────────────────────────────────────
# Helper functions
# ──────────────────────────────────────────────

_toml_escape() {
	local val="$1"
	# Escape backslashes and double quotes for TOML strings
	val=$(printf '%s' "$val" | sed 's/\\/\\\\/g; s/"/\\"/g')
	printf '%s' "$val"
}

_get_opt() {
	local section="$1"
	local option="$2"
	local default="$3"
	local val
	val=$(uci -q get "${UCI_CONF}.${section}.${option}" 2>/dev/null)
	if [ -z "${val}" ]; then
		printf '%s' "${default}"
	else
		printf '%s' "${val}"
	fi
}

_get_bool() {
	local section="$1"
	local option="$2"
	local default="$3"
	local val
	val=$(uci -q get "${UCI_CONF}.${section}.${option}" 2>/dev/null)
	case "${val}" in
		1|true|on|yes) printf 'true' ;;
		0|false|off|no|"") printf "${default}" ;;
		*) printf "${val}" ;;
	esac
}

# Write TOML array from comma-separated string
# Usage: _write_toml_array "customDomains" "a.com,b.com,c.com"
# Output: customDomains = ["a.com", "b.com", "c.com"]
_write_toml_array() {
	local key="$1"
	local input="$2"
	local result=""
	local item
	for item in $(echo "${input}" | tr ',' ' '); do
		item=$(printf '%s' "$item" | sed 's/^ *//; s/ *$//')
		if [ -n "$item" ]; then
			if [ -n "$result" ]; then
				result="${result}, "
			fi
			result="${result}\"${item}\""
		fi
	done
	if [ -n "$result" ]; then
		echo "${key} = [${result}]"
	fi
}

# ──────────────────────────────────────────────
# Write TOML header
# ──────────────────────────────────────────────

{
	echo "# This file is auto-generated by /usr/lib/frpc/generate_toml.sh"
	echo "# Do NOT edit manually. Changes will be overwritten."
	echo "# Generated at: $(date '+%Y-%m-%d %H:%M:%S')"
	echo ""
} > "${OUTPUT_TMP}"

# ──────────────────────────────────────────────
# Common section (server + auth + transport)
# ──────────────────────────────────────────────

MAIN_SECTION="main"

server_addr=$(_get_opt "${MAIN_SECTION}" "server_addr" "")
server_port=$(_get_opt "${MAIN_SECTION}" "server_port" "7000")
token=$(_get_opt "${MAIN_SECTION}" "token" "")
tls_enabled=$(_get_bool "${MAIN_SECTION}" "tls" "false")
server_name=$(_get_opt "${MAIN_SECTION}" "server_name" "")
auth_method=$(_get_opt "${MAIN_SECTION}" "auth_method" "token")

if [ -z "${server_addr}" ]; then
	echo "generate_toml.sh: ERROR: server_addr is empty, cannot generate config" >&2
	rm -f "${OUTPUT_TMP}"
	exit 1
fi

{
	echo "# ──────────────────────────────────────"
	echo "# Common settings"
	echo "# ──────────────────────────────────────"
	echo ""
	echo "serverAddr = \"$(_toml_escape "${server_addr}")\""
	echo "serverPort = ${server_port}"
	echo ""

	# Authentication
	echo "[auth]"
	echo "method = \"${auth_method}\""
	if [ -n "${token}" ]; then
		echo "token = \"$(_toml_escape "${token}")\""
	fi
	echo ""

	# Transport / TLS
	echo "[transport.tls]"
	if [ "${tls_enabled}" = "true" ]; then
		echo "enable = true"
		if [ -n "${server_name}" ]; then
			echo "serverName = \"$(_toml_escape "${server_name}")\""
		fi
	else
		echo "enable = false"
	fi
	echo ""
} >> "${OUTPUT_TMP}"

# ──────────────────────────────────────────────
# Proxy sections
# ──────────────────────────────────────────────

{
	echo "# ──────────────────────────────────────"
	echo "# Proxies"
	echo "# ──────────────────────────────────────"
	echo ""
} >> "${OUTPUT_TMP}"

# Iterate over all 'proxy' sections in UCI config
proxy_sections=$(uci -q show "${UCI_CONF}" 2>/dev/null | grep '=proxy$' | sed 's/=proxy$//' | sed 's/.*\.//')

for sid in ${proxy_sections}; do
	# Skip disabled proxies
	p_enabled=$(_get_bool "${sid}" "enabled" "true")
	if [ "${p_enabled}" != "true" ]; then
		continue
	fi

	p_name=$(_get_opt "${sid}" "name" "")
	p_type=$(_get_opt "${sid}" "type" "tcp")
	p_local_ip=$(_get_opt "${sid}" "local_ip" "127.0.0.1")
	p_local_port=$(_get_opt "${sid}" "local_port" "")
	p_remote_port=$(_get_opt "${sid}" "remote_port" "")
	p_custom_domains=$(_get_opt "${sid}" "custom_domains" "")
	p_subdomain=$(_get_opt "${sid}" "subdomain" "")
	p_plugin_type=$(_get_opt "${sid}" "plugin_type" "")
	p_plugin_user=$(_get_opt "${sid}" "plugin_user" "")
	p_plugin_pass=$(_get_opt "${sid}" "plugin_pass" "")
	p_plugin_local_path=$(_get_opt "${sid}" "plugin_local_path" "")
	p_plugin_strip_prefix=$(_get_opt "${sid}" "plugin_strip_prefix" "")
	p_plugin_http_user=$(_get_opt "${sid}" "plugin_http_user" "")
	p_plugin_http_passwd=$(_get_opt "${sid}" "plugin_http_passwd" "")
	p_plugin_addr=$(_get_opt "${sid}" "plugin_addr" "")
	p_encryption=$(_get_opt "${sid}" "use_encryption" "")
	p_compression=$(_get_opt "${sid}" "use_compression" "")
	p_bandwidth_limit=$(_get_opt "${sid}" "bandwidth_limit" "")
	p_bandwidth_limit_mode=$(_get_opt "${sid}" "bandwidth_limit_mode" "")
	p_pool_count=$(_get_opt "${sid}" "pool_count" "")
	p_health_check_type=$(_get_opt "${sid}" "health_check_type" "")
	p_health_check_timeout_s=$(_get_opt "${sid}" "health_check_timeout_s" "")
	p_health_check_max_failed=$(_get_opt "${sid}" "health_check_max_failed" "")
	p_health_check_interval_s=$(_get_opt "${sid}" "health_check_interval_s" "")
	p_http_user=$(_get_opt "${sid}" "http_user" "")
	p_http_pwd=$(_get_opt "${sid}" "http_pwd" "")
	p_locations=$(_get_opt "${sid}" "locations" "")
	p_transport_type=$(_get_opt "${sid}" "transport_type" "")
	p_proxy_protocol_version=$(_get_opt "${sid}" "proxy_protocol_version" "")
	p_secret_key=$(_get_opt "${sid}" "secret_key" "")
	p_role=$(_get_opt "${sid}" "role" "")
	p_server_name=$(_get_opt "${sid}" "server_name" "")
	p_sni_rewrite=$(_get_opt "${sid}" "sni_rewrite" "")

	# Skip if no name
	if [ -z "${p_name}" ]; then
		continue
	fi

	# Skip if no local port and no plugin
	if [ -z "${p_local_port}" ] && [ -z "${p_plugin_type}" ]; then
		continue
	fi

	# Validate proxy type
	case "${p_type}" in
		tcp|udp|http|https|stcp|xtcp|sudp) ;;
		*)
			echo "generate_toml.sh: WARNING: unknown proxy type '${p_type}' for '${p_name}', skipping" >&2
			continue
			;;
	esac

	# ──────────────────────────────────────
	# Emit [[proxies]] block
	# frp TOML format: [[proxies]] with type field inside
	# ──────────────────────────────────────

	{
		echo "[[proxies]]"
		echo "name = \"${p_name}\""
		echo "type = \"${p_type}\""

		# Common proxy fields
		if [ -n "${p_local_ip}" ]; then
			echo "localIP = \"${p_local_ip}\""
		fi

		if [ -n "${p_local_port}" ]; then
			echo "localPort = ${p_local_port}"
		fi

		# Type-specific fields
		case "${p_type}" in
			tcp|udp|sudp)
				if [ -n "${p_remote_port}" ]; then
					echo "remotePort = ${p_remote_port}"
				fi
				;;
			http|https)
				if [ -n "${p_custom_domains}" ]; then
					_write_toml_array "customDomains" "${p_custom_domains}"
				fi
				if [ -n "${p_subdomain}" ]; then
					echo "subdomain = \"${p_subdomain}\""
				fi
				;;
			stcp|xtcp)
				if [ -n "${p_role}" ]; then
					echo "role = \"${p_role}\""
				fi
				if [ -n "${p_secret_key}" ]; then
					echo "secretKey = \"${p_secret_key}\""
				fi
				if [ -n "${p_server_name}" ] && [ "${p_role}" = "visitor" ]; then
					echo "serverName = \"${p_server_name}\""
				fi
				;;
		esac

		# Plugin configuration
		# In frp TOML: [proxies.plugin] is a sub-table of the last [[proxies]]
		if [ -n "${p_plugin_type}" ]; then
			echo ""
			echo "[proxies.plugin]"
			echo "type = \"${p_plugin_type}\""
			case "${p_plugin_type}" in
				socks5|http_proxy|http2socks)
					if [ -n "${p_plugin_user}" ]; then
						echo "user = \"${p_plugin_user}\""
					fi
					if [ -n "${p_plugin_pass}" ]; then
						echo "passwd = \"${p_plugin_pass}\""
					fi
					;;
				static_file)
					if [ -n "${p_plugin_local_path}" ]; then
						echo "localPath = \"${p_plugin_local_path}\""
					fi
					if [ -n "${p_plugin_strip_prefix}" ]; then
						echo "stripPrefix = \"${p_plugin_strip_prefix}\""
					fi
					if [ -n "${p_plugin_http_user}" ]; then
						echo "httpUser = \"${p_plugin_http_user}\""
					fi
					if [ -n "${p_plugin_http_passwd}" ]; then
						echo "httpPasswd = \"${p_plugin_http_passwd}\""
					fi
					;;
				unix_domain_socket)
					if [ -n "${p_plugin_addr}" ]; then
						echo "unixPath = \"${p_plugin_addr}\""
					fi
					;;
				sni)
					if [ -n "${p_sni_rewrite}" ]; then
						echo "sniRewrite = \"${p_sni_rewrite}\""
					fi
					;;
				*)
					if [ -n "${p_plugin_user}" ]; then
						echo "user = \"${p_plugin_user}\""
					fi
					if [ -n "${p_plugin_pass}" ]; then
						echo "passwd = \"${p_plugin_pass}\""
					fi
					;;
			esac
		fi

		# Transport options (dot notation within [[proxies]])
		if [ -n "${p_encryption}" ]; then
			echo "transport.useEncryption = ${p_encryption}"
		fi
		if [ -n "${p_compression}" ]; then
			echo "transport.useCompression = ${p_compression}"
		fi
		if [ -n "${p_transport_type}" ]; then
			echo "transport.protocol = \"${p_transport_type}\""
		fi
		if [ -n "${p_proxy_protocol_version}" ]; then
			echo "transport.proxyProtocolVersion = \"${p_proxy_protocol_version}\""
		fi
		if [ -n "${p_bandwidth_limit}" ]; then
			echo "transport.bandwidthLimit = \"${p_bandwidth_limit}\""
			if [ -n "${p_bandwidth_limit_mode}" ]; then
				echo "transport.bandwidthLimitMode = \"${p_bandwidth_limit_mode}\""
			fi
		fi
		if [ -n "${p_pool_count}" ]; then
			echo "transport.poolCount = ${p_pool_count}"
		fi

		# Health check (dot notation within [[proxies]])
		if [ -n "${p_health_check_type}" ]; then
			echo "healthCheck.type = \"${p_health_check_type}\""
			if [ -n "${p_health_check_timeout_s}" ]; then
				echo "healthCheck.timeoutSeconds = ${p_health_check_timeout_s}"
			fi
			if [ -n "${p_health_check_max_failed}" ]; then
				echo "healthCheck.maxFailed = ${p_health_check_max_failed}"
			fi
			if [ -n "${p_health_check_interval_s}" ]; then
				echo "healthCheck.intervalSeconds = ${p_health_check_interval_s}"
			fi
		fi

		# HTTP basic auth (for http/https proxies)
		if [ -n "${p_http_user}" ]; then
			echo "httpUser = \"${p_http_user}\""
		fi
		if [ -n "${p_http_pwd}" ]; then
			echo "httpPassword = \"${p_http_pwd}\""
		fi

		# URL locations (for http proxies)
		if [ -n "${p_locations}" ]; then
			# Use sed to convert newline-separated locations to TOML array
			# POSIX-compatible: no bashisms
			loc_array=$(printf '%s\n' "${p_locations}" | sed '/^$/d; s/^ *//; s/ *$//; s/.*/"&"/' | tr '\n' ',' | sed 's/,$//')
			if [ -n "$loc_array" ]; then
				echo "locations = [${loc_array}]"
			fi
		fi

		echo ""
	} >> "${OUTPUT_TMP}"
done

# ──────────────────────────────────────────────
# Move temp file to final location
# ──────────────────────────────────────────────

mv -f "${OUTPUT_TMP}" "${OUTPUT}"
chmod 600 "${OUTPUT}"

echo "generate_toml.sh: Successfully generated ${OUTPUT}"
